import Head from "next/head";

import Inner from "@/components/Layout/Inner";
import HomeIndex from "./(Home)/_components";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Victor Essien | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/images/profile_6.jpg"
          style={{ width: "60px", height: "60px", borderRadius: "50%" }}
        />
      </Head>
      <Inner>
        <HomeIndex />
      </Inner>
    </div>
  );
}
