import Head from 'next/head'
import Inner from '@/components/Layout/Inner'
import Work from './_components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Victor Essien | WORK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/profile_6.jpg"
          style={{ width: "60px", height: "60px", borderRadius: "50%" }}
        />
      </Head>
      <Inner>
        <Work/>
      </Inner>
    </>
  );
}
